default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
full-dark: styles/full-dark.scss
tangerine: styles/tangerineui.scss
tangerine-purple: styles/tangerineui-purple.scss
